name: CI/CD Pipeline

on:
  push:
    branches: [feat/pnpm]
  pull_request:
    branches: [feat/pnpm]

env:
  GHR_PROJECT_REPONAME: ui5-language-assistant
  GHR_PROJECT_USERNAME: SAP

jobs:
    build:
        strategy:
          matrix:
            os: [windows-latest]
            node-version: [18.x]
        runs-on: ${{ matrix.os }}
        steps:
        - name: Checkout code repository
          uses: actions/checkout@v4
          with:
              fetch-depth: 0     
        - name: Set up Husky
          run: npx husky install     
        - name: Setup pnpm
          uses: pnpm/action-setup@v4
          with:
              run_install: true
        - name: Cache pnpm modules
          uses: actions/cache@v4
          env:
              cache-name: cache-pnpm-modules
          with:
              path: ~/.pnpm-store
              key: ${{ matrix.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
              restore-keys: |
                  ${{ matrix.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v4
          with:
              node-version: ${{ matrix.node-version }}
        - name: Install pnpm modules
          run: pnpm install
        - name: Run build
          run: pnpm run build
        # - name: Run unit tests
        #   run: pnpm run test